# This file intentionally left blank
BLUETOOTH_ENABLE = yes
BLUETOOTH_DRIVER = bluefruit_le
F_CPU = 8000000

CUSTOM_MATRIX = yes
SRC += icebreaker_bt.c matrix.c
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
